export default {
    LEFT_KEY: 37,
    RIGHT_KEY: 39,
    UP_KEY: 38,
    DOWN_KEY: 40,
    SNAKE_PIECE_WIDTH: 20,
    SNAKE_PIECE_HEIGHT: 20,
    SNAKE_SIZE: 20,
    SNAKE_COLOR: 'red',
    SNAKE_FOOD_COLOR: 'blue',
    STROKE_COLOR: '#000',
    RIGHT: "RIGHT",
    LEFT: "LEFT",
    UP: "UP",
    DOWN: "DOWN",
    CURRENT_DIRECTION: "RIGHT",
};