export default {
    LEFT_KEY: 37,
    RIGHT_KEY: 39,
    UP_KEY: 38,
    DOWN_KEY: 40,
    SNAKE_PIECE_WIDTH: 20,
    SNAKE_PIECE_HEIGHT: 20,
    SNAKE_COLOR: 'red',
    STROKE_COLOR: '#000',
    SNAKE_SPEED: 80,
    CURRENT_DIRECTION: "RIGHT",
};